services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_v3
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8088:8088"
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8088"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db_v3_sild
    restart: always
    environment:
      MYSQL_DATABASE: laravel_v3
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql_db_v3_sild

  vite:
    image: node:20
    container_name: vite_v3
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - app

volumes:
  dbdata:
